### ISSUE TITLE
concept search fails

### ISSUE THREAD

**Issue by lonnylundsten** [mbari-media-management/vars-annotation#10]
Concept search fails and, although I can't pinpoint what is causing the fail, it seems as if refreshing the DB in the Bulk Editor window causes the issue. After I refresh the DB in the "Bulk Editor' window, when bulk changing Activity, searching and entering new concepts fails. The solution is to restart vars.

**Comment by lonnylundsten** [comment]
When this happens, the concept defaults to 1-gallon paint bucket. No other concepts can be selected.

**Comment by hohonuuli** [comment]
@lonnylundsten You'll need to demo this issue to me. I'm not clear on what's actually happening. Most likely we'll have to wait until Monday to review this.

**Comment by hohonuuli** [comment]
Wierd behavior the fix was:

```java
@@ -231,12 +232,10 @@ public class AnnotationEditorPaneController {
         toolBox.getServices()
                 .getConceptService()
                 .findAllNames()
-                .thenApply(names -> {
-                    ObservableList<String> cns = FXCollections.observableArrayList(names);
-                    Platform.runLater(() -> {
-                        conceptComboBox.setItems(cns);
-                    });
-                    return null;
+                .thenAccept(names -> {
+
+                    FilteredList<String> cns = new FilteredList<>(FXCollections.observableArrayList(names));
+                    Platform.runLater(() -> conceptComboBox.setItems(cns));
                 });
     }
```

**Comment by hohonuuli** [comment]
Just to clarify, when @lonnylundsten used the main refresh button. The main concept search combobox would not run a search. It would just pop up the items list and show the tool tip, but no filtering was occurring. It looks like I was setting the items correctly. Running tests with similar usage demonstrated that it worked. When I wrap it in a filtered list, the FilteredComboboxDecorator does less work, which seemed to fix the issue although I'm not sure why we were running into it in the first place.

**Comment by lonnylundsten** [comment]
This one is still not fixed. I just downloaded the newest release, refreshed and the concept defaults to 1-gallon paint bucket.

**Comment by hohonuuli** [comment]
As a temporary workaround, I've disable the refresh in [AnnotationEditorPaneController](https://github.com/mbari-media-management/vars-annotation/commit/9dce1666aad0470fa98b521ad1fdc1227a62c585#diff-b7935e1dc66264c4c91155dc67e1b856L178). So the comboBox doesn't get refreshed, but it doens't stop working either.

**Comment by hohonuuli** [comment]
This workaround was applied in alpha-4. Moving this to the next alpha for resolution
