### ISSUE TITLE
Adding a "detail" drop down box doesn't work correctly

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#101]
Sample: annotated "anchor", want to add "retrieved-by", then pick manipulator. The "to" link doesn't respond to alpha searching; you have to scroll all the way through all equipment to choose manipulator. See screen grab attached.
<img width="916" alt="screen shot 2018-12-18 at 8 14 54 am" src="https://user-images.githubusercontent.com/38045059/50167359-dbaa4180-029d-11e9-87c5-893d80fff3cc.png">

**Comment by hohonuuli** [comment]
The relevant code is at [AssociationEditorPaneController.java:132](https://github.com/mbari-media-management/vars-annotation/blob/master/src/main/java/org/mbari/m3/vars/annotation/ui/roweditor/AssociationEditorPaneController.java#L132). That combobox has the `FilteredComboboxDecorator`, which doe the filtering popup,  but it may have a bad interaction with the `HierarchicalComboboxDecorator`. I'll look into it.
