### ISSUE TITLE
Dives will not open on non-10G connections

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#104]
No load bar appears even after ~5 minutes. Tried numerous dives. Non-critical, but wanted you to know as we continue to optimize.

**Comment by lindakuhnz** [comment]
Tried again. Still true in A130.

**Comment by NancyJS** [comment]
Weird! Anyone else having this problem on their office machines?

**Comment by hohonuuli** [comment]
Kyra had this issue at the end of last week. She also was unable to open videos in Final Cut. So I don't believe it's VARS related. I suspect something is going on with the network.

**Comment by hohonuuli** [comment]
Also, You should check with IS to make sure that they aren't running a big job on Atlas or Titan. If I remember correctly, that may have been the source of Kyra's woes.

**Comment by lindakuhnz** [comment]
Note that this regards non-10G connection.

No wifi on, A130, regular (non-10G network) Bathysphere.
Tried opening the following data sets. 
V3810-01 (5000 annotations), no loading bar comes up after 5 minutes (annotated from tapes)
V2536-01 (1700 annotations), no loading bar comes up after 5 minutes (annotated from tapes)
D008-01, (~50 annotations) no loading bar comes up after 5 minutes (annotated from tapes)
D1036 loads fine (~20 annotations for one 15 minute segment) annotated from video files
D1100 loads fine (~25 annotations for one 15 minute segment) annotated from video files

**Comment by hohonuuli** [comment]
I was able to open V3810-01 over WiFi in Tank View with no issues.

**Comment by lindakuhnz** [comment]
We have now discovered that this is probably an issue regarding not having a tape deck attached.

**Comment by lindakuhnz** [comment]
Please reopen.

**Comment by hohonuuli** [comment]
Check to see if a failure to connect to a backmagic device or tape deck is hanging the application.

**Comment by lindakuhnz** [comment]
2 issues: 
1) caused when no tape deck or other capture device attached
2) Lonny and Brian we opening the dives using the “Open video asset manager”; scroll through the lists, vs. opening the "Open tape” and typing in the number.
