### ISSUE TITLE
Changing M3 annotations from Bathyphasma ovigerum to Careproctus overigerus

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#105]
Continued taxonomic dispute on this name (see DSG notes).

**Comment by lindakuhnz** [comment]
UPDATE annotations SET concept = 'Careproctus ovigerus' WHERE concept = 'Bathyphasma ovigerum'

**Comment by lindakuhnz** [comment]
was as an association; fixed.

**Comment by NancyJS** [comment]
Thanks. Yeah, I could see that, but shouldn’t those also get replaced in a global replace?
