### ISSUE TITLE
Opening VARS for Images on PC Windows 10

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#107]
We are using VARS for images a lot and there is an odd bug when running it on the Mac. We will be using it heavily in the coming couple of weeks, and thus I’m trying to see about running it on a PC. We don’t have a PC in the VL any more so trying to run it via VMWare. Windows 10 keeps asking me for what app to open it with and I don’t see any way to direct it to Java. Help!

**Comment by hohonuuli** [comment]
Follow these instructions for setting `JAVA_HOME` on Windows: <https://docs.oracle.com/cd/E19182-01/820-7851/inst_cli_jdk_javahome_t/>
