### ISSUE TITLE
Deep Sea Guide errors

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#109]
The "view data products for this region" pulldown menu is missing, so we cannot search by the region. Example:

[http://seaspray.shore.mbari.org:8080/dsg/plots/concept/Sternostylus/Global](http://seaspray.shore.mbari.org:8080/dsg/plots/concept/Sternostylus/Global)

The "map of this region" link errors out as well ("For development purposes only" appears across it numerous times). This has been like this for a while, while the above issue is relatively new.

**Comment by hohonuuli** [comment]
No data products yet exist for _Sternostylus_. The data product generator is currently shutdown until it's rewritten for the new M3 system.

**Comment by lindakuhnz** [comment]
Ok, I see. This was a name change and the data is available, but would not have been processed to DSG for either the external or internal DSG (is this right?), solving the mystery of no drop-down menu. 
Do look at what is happening to the maps, however. See attached or look live at say, Bathyraja abyssicola. Same issue that maps can't be processed? Thanks.
![screen shot 2019-02-25 at 1 31 08 pm](https://user-images.githubusercontent.com/38045059/53370268-2a113780-3902-11e9-9bb1-4da4bda91499.png)
