### ISSUE TITLE
Please restore link to VARS scripts for canadian grid measurements

### ISSUE THREAD

**Issue by chuffard** [mbari-media-management/vars-annotation#112]
On:

atlas/VARS_Stn-M_Image_Archive/howto/measurements.html

please restore link halfway down the page to point to:

vars-queryparsing-1.1.5 

which I think is the latest version.

thanks!

**Comment by hohonuuli** [comment]
Links are restored. Note that the Documentation page at `//Atlas/VARS_Stn-M_Image_Archive/Documentation.html` has links to all the downloadable applications now.
