### ISSUE TITLE
VARS query for PC

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#114]
From Brian:
I’m having some issues with the MSI file. As a workaround for non-Mac users, if they have Java 8 installed they can use either:

vars-query-1.0-app.jar - On some platforms, just double clicking it will launch it. Or from a terminal: `java -jar vars-query-1.0-app.jar`
vars-query-1.0-pack.zip - Unzip this file. Theres a bin directory with launch scripts for Mac, Windows, and Linux.
Apologies for the issues with Windows. Due to all the recent major changes in Java, I’m still waiting for the tools to catch up so that I can produce self-contained apps that don’t require an externally installed Java. Windows is particularly problematic.

**Comment by lindakuhnz** [comment]
Is there a way to leave this here, but place it on hold?

**Comment by hohonuuli** [comment]
The java packager included in JDK 8 ([Amazon Corretto](https://aws.amazon.com/corretto/)) builds the MSI file for Windows. But the MSI fails to install. Note that the packager is what I use to build the app for Mac and deb file for Linux. A [new packager](https://mail.openjdk.java.net/pipermail/openjfx-dev/2018-September/022500.html) [might be included in Java 13](https://openjdk.java.net/jeps/343), due this fall. At which time, I'll need to eat the whole JDK 11+ elephant (Issue #40)

- <https://blogs.oracle.com/jtc/a-brief-example-using-the-early-access-jpackage-utility>

**Comment by hohonuuli** [comment]
Moved the issue to vars-query project.
