### ISSUE TITLE
VARS annotation shore time display 

### ISSUE THREAD

**Issue by lonnylundsten** [mbari-media-management/vars-annotation#117]
Please display additional time data in the VARS shore GUI. When annotating we need to see the additional time ( is it 100th of a second or millisecond time unit) in the GUI -- see red box on attached screen grab. Also please make this time display bold and a slightly larger font.
Thanks,
LL

![Screen Shot 2019-06-12 at 9 39 10 AM](https://user-images.githubusercontent.com/32526132/59369994-75572680-8cf6-11e9-8ba6-4babbcd48e1c.png)

**Comment by hohonuuli** [comment]
> When annotating we need to see the additional time

Ok. Careful what you wish for. I'll roll this out in the next VARS release (date TBD)
