### ISSUE TITLE
package sharktopoda within VARS

### ISSUE THREAD

**Issue by lonnylundsten** [mbari-media-management/vars-annotation#12]
This is not a priority but a suggestion....it would make VARS very user friendly.....I think that sharktopoda should be embedded within the VARS app, so to the user it just looks like one thing. When you open a video file with the new VARS, the file opens using the sharktopoda player but that happens behind the scenes and the user doesn't have to install and start sharktopoda separately.

**Comment by hohonuuli** [comment]
> sharktopoda should be embedded within the VARS app

That I don't think is really feasible.

With Java 9, there's improvements to the [Process](https://docs.oracle.com/javase/9/docs/api/java/lang/Process.html) API that will allow better control of external applications. So, at some point, we could have VARS launch Sharktopoda if it's not already running.

**Comment by hohonuuli** [comment]
But don't upgrade to Java 9 yet!! It doesn't play well with the current VARS systems.
