### ISSUE TITLE
VARS crashing a lot

### ISSUE THREAD

**Issue by mkbassett** [mbari-media-management/vars-annotation#121]
Hi, 

VARS has crashed a lot today.

It crashed when:
- I tried to take a frame grab. It sounds like Kyra was having this problem with tapes as well yesterday.
- I opened the preferences to make sure the frame grab settings were correct.
- It says it crashes when I manually close the app. 

VARS is also started loading all of the annotations for an entire dive after lunch today. I'm working on tape 6 of a dive and all annotations from previous tapes are showing up with the yellow lightning bolts. 

Attached are the logs from VARS- Lonny showed me how to collect them for this ticket. 

Let me know if you need anything else! 
[vars-annotation-01.log](https://github.com/mbari-media-management/vars-annotation/files/4834149/vars-annotation-01.log)
[vars-annotation.20200625.log](https://github.com/mbari-media-management/vars-annotation/files/4834150/vars-annotation.20200625.log)
[vars-annotation-00.log](https://github.com/mbari-media-management/vars-annotation/files/4834152/vars-annotation-00.log)

**Comment by hohonuuli** [comment]
@mkbassett Kyra said version 0.5.1 was working for her with framecapture for tapes. Try that version from <http://m3.shore.mbari.org/apps> and see if it works for you.

To fix the issue where all the annotations are appearing, try this: 

1. Merge the dive you're working on so annotations get timestamped correctly
2. Open each tape in VARS. When you close VARS or open a different tape/video, VARS will correctly set the start time and duration of a tape based on the annotation data. That should make the overlapping annotations disappear, unless the dive had the timecode reset during the dive. In that case there's not much I can do.

**Comment by hohonuuli** [comment]
I logged this at <https://mbari1.atlassian.net/browse/M3-132>
