### ISSUE TITLE
make custom buttons able to be rearranged

### ISSUE THREAD

**Issue by MeaganPutts** [mbari-media-management/vars-annotation#125]
Like with the concept names, it would be helpful if the custom annotation buttons could be rearranged and sortable as new buttons are created to make it easier to find the button you would like to use. Tabs might be nice as well to keep buttons organized by category like size, substrate, comment, ect.

**Comment by hohonuuli** [comment]
Related to #27

**Comment by hohonuuli** [comment]
This has been added since [release 1.1.14](https://github.com/mbari-media-management/vars-annotation/releases/tag/1.1.14)
