### ISSUE TITLE
VARS is not running correctly on macOS Ventura

### ISSUE THREAD

**Issue by hohonuuli** [mbari-media-management/vars-annotation#135]
From Lonny:

Just wanted to give you a heads up that there are issues with MacOS Ventura and VARS.

1. Terminal needs full disk access to run xattr
	- this will likely need to be reinstated, even if it had access before 

2. After that, when you first try to open vars, you need to look in the Privacy & Security preference pane and ‘allow’ vars to be opened — see attached.

3. Once VARS is able to be opened the video asset view is ‘blank’ — see attached.

4. If I use the ‘finder’ method of opening a video file, VARS says ‘Unable to find matching video by name, the video you are opening does not exist in the video asset manager.
	— See attached screen grab. Larissa opened this video fine on her annotation station running macOS Monterey.

![Security_setting](https://user-images.githubusercontent.com/282941/197631394-0858def7-504a-4336-92f3-da197345eeea.png)

![VARS video asset manager](https://user-images.githubusercontent.com/282941/197631412-54942c3d-2a89-427f-ae4a-a1970e8b13d1.png)

![error_opening_file](https://user-images.githubusercontent.com/282941/197631425-c560fc13-1666-4a10-937f-f69c91e569d8.png)

**Comment by hohonuuli** [comment]
Did some testing with Lonny. There's an extra step in the security preferences but VARS is able to run fine on Ventura otherwise.

**Comment by lonnylundsten** [comment]
I'm continuing to test on Ventura and will make notes about issues here:

1. VARS keeps losing connection to the video. As an example, all was fine, then I responded to an email and when I came back to VARS the video was no longer playable, seeable, or annotatable. 

2. Often two video files open when I open videos with the VARS Asset Manager or Finder (doesn't always happen).

3. Asset Manager is slow to draw window data, i.e., he window is blank, then assets show, then I browse to the folder, which is empty at first, then it draws, etc., etc. The GUI seems slow and not as responsive as normal.

**Comment by nikkicunanan** [comment]
> Did some testing with Lonny. There's an extra step in the security preferences but VARS is able to run fine on Ventura otherwise.

Just received my new laptop with macOS Ventura 13.0.1, and VARS won't open the video files. 
Can you walk me through the "extra security step" that needs to be done in order to run VARS, please?
Mahalo!

**Comment by hohonuuli** [comment]
@nikkicunanan did you follow the steps at < https://docs.mbari.org/vars-annotation/setup/>?

**Comment by nikkicunanan** [comment]
@hohonuuli Tried it this morning, and it works. However, there was one issue when running the test.
"X NOT FOUND beholder"
<img width="1728" alt="Screenshot 2022-11-21 at 7 27 12 AM" src="https://user-images.githubusercontent.com/115189321/203127369-4fb6bc49-b720-4598-9d56-a3b313ec237e.png">

Is this an issue that needs to be addressed? Other than that, VARS seems to be working fine. Mahalo!

**Comment by hohonuuli** [comment]
VARS is now being used in the video lab on Ventura. No issues have been reported.

**Comment by hohonuuli** [comment]
No regressions on Ventana. All is well. Closing this issue.
