### ISSUE TITLE
activity should be populated with camera directions from existing VARS

### ISSUE THREAD

**Issue by lonnylundsten** [mbari-media-management/vars-annotation#14]
The activity field should be pre-populated with camera directions from the existing VARS annotation app. Typing activity manually is going to create problems with empty fields and misspellings.

**Comment by hohonuuli** [comment]
The activity should already be pre-populated. Did you mean pre-selected?

**Comment by lonnylundsten** [comment]
Activity is not pre-populated when annotating a new file.

**Comment by hohonuuli** [comment]
Turns out this isn't an issue. They are working as expected. But just to clarify. The activity and group comboboxes display all values that have been used in the database. If you need a different value, you will need to manually enter it in.
