### ISSUE TITLE
Add indexes to deepsea-ai/M3_EVENT_TRACKS database.

### ISSUE THREAD

**Issue by hohonuuli** [mbari-media-management/vars-annotation#145]
Currently there are only indices on the primary keys. The `Event` table had 91 million rows, so definitely needed. 

cc: @danellecline

**Comment by danellecline** [comment]
Whoa.  Thanks for looking into that.  Fingers crossed this will help

**Comment by hohonuuli** [comment]
Attempting to add the following but it's running slooooooooow 

```sql
CREATE INDEX Event_track_uuid_index
   ON dbo.Event (track_uuid)
GO
```

**Comment by hohonuuli** [comment]
@danellecline The indexes will make a huge difference. I'll add them to any column that is used for search (e.g. Event.media_id, Event.class_id, etc).

**Comment by hohonuuli** [comment]
Adding 

```sql
create index Event_media_id_index
    on dbo.Event (media_id)
go
```

**Comment by hohonuuli** [comment]
Media table:

```sql
create index Media_job_id_index
    on dbo.Media (job_id)
go

create index Media_uuid_index
    on dbo.Media (uuid)
go

```

**Comment by hohonuuli** [comment]
Running the following still took 45 seconds. Look at views to see how they are constructed ...

```sql
select
    *
from
    Track
where
    media_id = 44
```

**Comment by hohonuuli** [comment]
Running `SELECT * FROM Event WHERE media_id = 44` returns 53100 records in 741ms

**Comment by hohonuuli** [comment]
Additional indices could be created on Job and User but they're so small I'm skipping.
