### ISSUE TITLE
Add ability to see whole dive in video sequence viewer

### ISSUE THREAD

**Issue by hohonuuli** [mbari-media-management/vars-annotation#22]
Need to see the whole dive. Only seeing 15 min. at a time makes it difficult and inconsistent to annotate – a solution might be to display a separate window similar to video set.

**Comment by lindakuhnz** [comment]
Need ability to edit whole dive (replaces VARS video tape set)

**Comment by hohonuuli** [comment]
Added in Release 0.2.1
