### ISSUE TITLE
Finish bulk editor

### ISSUE THREAD

**Issue by hohonuuli** [mbari-media-management/vars-annotation#25]
Neither the concept or details (change/replace/delete associations) section of the bulk editor work yet.

**Comment by hohonuuli** [comment]
Also, In bulk editor, delineate the fields with boxes (or similar) instead of lines with arrows, which are not intuitive visual indicators

**Comment by lindakuhnz** [comment]
Some examples: can't add associations to multiple annotations, pull down selection box does not work; typing m doesn't get you to manipulator; you have to scroll through the whole list of details

**Comment by hohonuuli** [comment]
Pending task is to implement the 'replace association' feature.
