### ISSUE TITLE
Integrate Shuttle Pro for playback control

### ISSUE THREAD

**Issue by hohonuuli** [mbari-media-management/vars-annotation#33]
Also (or), can we integrate SDK kit from Shuttle Pro (Contour Designs https://www.contourdesign.com/product/shuttlepro-v2/) so that VARS or Sharktopoda can use it?

**Comment by hohonuuli** [comment]
I sent a request for more info and/or the SDK to <https://www.contourdesign.com/contact/> today

**Comment by hohonuuli** [comment]
Response from Countour:

Hi Brian,

> Thanks for reaching out to us. We do have some SDK files available, please keep in mind that they’re somewhat dated and may require some tinkering to get to work fully. Here’s the link to the Windows SDK development file:
> 
> <https://www.dropbox.com/s/cc8iuameg6dijcc/Shuttle_Windows_SDK_Distribution.zip?dl=0>
> 
> And here’s the link to the Mac SDK:
> 
> <https://www.dropbox.com/s/1tfle8oxoklydkf/ContourShuttleDeveloperOSX.zip?dl=0>
> 
> Please let me know if you have any issues downloading the files.
> 
> Sincerely,
> 
> l Neil Moyer
> l Technical Support Specialist
> l Contour Design, Inc.
> l 10 Industrial Drive I Windham, NH I 03087
> l P: (603)893-4556
> l www.contourdesign.com

**Comment by hohonuuli** [comment]
@NancyJS Do we have a ShuttlePro that I can use for a while to develop this? If not can the video lab order one for me to develop with? (Then I can return it to the video lab for use when I'm done with the integration)

**Comment by hohonuuli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Jog-wheel support](https://trello.com/c/uW80KFB4/17-jog-wheel-support)

**Comment by hohonuuli** [comment]
I installed the Contour Shuttle Pro drivers (v3.2), but was unable to get them to work correctly. [Apparently this is a common issue](https://forums.contourdesign.com/viewtopic.php?f=4&t=7998). I followed the extra instructions for Mac 10.4 listed on the driver site. I also uninstalled and reinstalled several times. At this point, I'm setting this task aside. It would just be one more thing that doesn't work well that needs to be supported. Lonny pointed out that when Sharktopoda is focused you can use a magic mouse or track pad with side-to-side scrolling to scrub through a movie. I'll suggest that as a workaround. In the meantime, I'll also add a few keystrokes for shuttle control to vars-annotation.

**Comment by hohonuuli** [comment]
Added the following key map for controlling video:

__Actions using Home Row__
```
Toggle Play/Stop                [alt]+K
Shuttle Forward (0.03)          [alt]+L
Shuttle Reverse (0.03)          [alt]+J
Shuttle Forward (0.06)          [alt]+;
Shuttle Reverse (0.06)          [alt]+H
Frameadvance                    [alt]+I
Seek +1 second                  [alt]+O
Seek -1 second                  [alt]+U
Stop                            [alt]+M
```

__Actions using Arrows__

```
Toggle Play/Stop                [alt]+down, [ctrl]+[space]
Frameadvance                    [alt]+up
Seek +1 second                  [alt]+left
Seek -1 second                  [alt]+right
```

__Other__

```
Toggle Play/Stop                [ctrl]+[space]
```

**Comment by hohonuuli** [comment]
OK, ignore that key map above. I'm moving the keys around as [alt]+some chars, is a way of getting non-ascii characters on a Mac. Use the map below:

__Video Actions using Home Row__

```
Toggle Play/Stop                [cmd]+K
Shuttle Forward (0.03)          [cmd]+L
Shuttle Reverse (0.03)          [cmd]+J
Shuttle Forward (0.06)          [cmd]+;
Shuttle Reverse (0.06)          [cmd]+H
Frameadvance                    [cmd]+I
Seek +1 second                  [cmd]+.
Seek -1 second                  [cmd]+,
```

__Actions using Arrows__

```
Toggle Play/Stop                [cmd]+down
Frameadvance                    [cmd]+up
Shuttle Forward (0.03)          [cmd]+right
Seek -1 second                  [cmd]+left
```

__Other__

```
Toggle Play/Stop                [ctrl]+[space]
Scroll up one row               [cmd]+[shift]+up
Scroll down one row             [cmd]+[shift]+down
New annotation                  [cmd]+N
Copy annotation to new time     [cmd]+G
Duplicate annotation            [cmd]+T
Frame capture                   [cmd]+F
Delete annotations              [cmd]+[delete]
Undo                            [cmd]+Z
Redo                            [cmd]+[shift]+Z
```

Note that on Windows/Linux substitude the [ctrl] key for the [cmd] key used above.

**Comment by hohonuuli** [comment]
I dropped the `[cmd]+H` shortcut, it will be gone in the next release. I forgot about the standard mac shortcut that hides the window, so I was getting a key collision.

**Comment by hohonuuli** [comment]
@lindakuhnz : You could take a shot at creating a mapping between these keys and the Contour Shuttle Pro to see if they will work for your usage.

**Comment by hohonuuli** [comment]
I'm closing this issue as the key map should allow for usage of the Shuttle Pro. Also just a note that if [Sharktopoda](https://github.com/mbari-media-management/Sharktopoda) has focus, you can use a magic mouse or track-pad to scrub back and forth using side-to-side swipes on the track surface.

**Comment by lonnylundsten** [comment]
I've got the keymapping working with the 3Dconnexion Space mouse. Will try getting it working for shuttle pro. The frame advance keymapping is great but we also need a frame backwards keymap.

**Comment by lonnylundsten** [comment]
> I dropped the `[cmd]+H` shortcut, it will be gone in the next release. I forgot about the standard mac shortcut that hides the window, so I was getting a key collision.

So what are we using in place of command+ H for Shuttle Reverse (0.06) ?

**Comment by lonnylundsten** [comment]
This is all working with the shuttle pro if we can get .6 shuttle reverse and frame reverse working.

**Comment by hohonuuli** [comment]
> .6 shuttle reverse

That's easy. I'll fix in the next release. Keep in mind that due to the nature of codecs videos generally do not play well backwards.

> frame reverse working

There's no frame reverse implemented in the video player. A single frame is a no-go. but we can take a small jump back in to time ... we have to make an assumption and decide if the jump is for a 60fps or 30fps video though.

**Comment by lonnylundsten** [comment]
If you can do a .25 or .10 s reverse keymap and replace the command-H (.6 reverse) keymap, then we can close this ticket. Woo hoo! Problem solved!
LL

Lonny Lundsten
Senior Research Technician

Monterey Bay Aquarium
Research Institute
7700 Sandholdt Road
Moss Landing, CA 95039
www.mbari.org/staff/lonny
lonny@mbari.org

**Comment by lonnylundsten** [comment]
> > .6 shuttle reverse
> 
> That's easy. I'll fix in the next release. Keep in mind that due to the nature of codecs videos generally do not play well backwards.
> 
> > frame reverse working
> 
> There's no frame reverse implemented in the video player. A single frame is a no-go. but we can take a small jump back in to time ... we have to make an assumption and decide if the jump is for a 60fps or 30fps video though.

Sharktapoda does have a -1 frame capability, as does quicktime. If I am using either one of those video players and I press the left arrow I go reverse 1 frame at a time; the right arrow will go forward one frame at a time.

**Comment by hohonuuli** [comment]
> Sharktapoda does have a -1 frame capability

Yes, the player does through it's UI but __not__ through it's remote interface control. See <https://github.com/mbari-media-management/Sharktopoda/blob/main/docs/REQUIREMENTS.md>

**Comment by lonnylundsten** [comment]
OK. Got it!
LL

**Comment by hohonuuli** [comment]
I'll be rolling out a new release of VARS in a few minutes. I've updated the keymap list above. The 2 notable changes: [cmd]+M is jump back .1 second. [cmd]+G is reverse shuttle 0.06

**Comment by lonnylundsten** [comment]
can you also add 1.5x, 2x, and maybe 3x keymaps?
