### ISSUE TITLE
Concept combobox doesn't play well with spaces

### ISSUE THREAD

**Issue by hohonuuli** [mbari-media-management/vars-annotation#34]
If typing in the concept box and you type the entire genus –space – species name, you won’t come up with the right concept, giving users a false sense of what may/not be in the KB

**Comment by hohonuuli** [comment]
This is known. The JavafX combobox eats spaces when the popup is open.

**Comment by lindakuhnz** [comment]
confirmed 4/3

**Comment by lindakuhnz** [comment]
Let us know when you are going to work on this, as we have other suggestions that will help us.

**Comment by hohonuuli** [comment]
Found a workaround for this. The root cause is a long-standing bug in the [_skin_ of a JavaFX combobox](https://bugs.openjdk.java.net/browse/JDK-8087549). I applied a [workaround I found on stackoverflow](https://stackoverflow.com/questions/50013972/how-to-prevent-closing-of-autocompletecombobox-popupmenu-on-space-key-press-in-j). It's kind of a hack that uses `com.sun` packages. When doing the port to JDK 11 (#40) these packages are moved to `javafx.scene.control.skin`. 

Note, that the workaround consumes the space keystroke. So the space won't appear in the pop up. `bird water sampler` would appear as `birdwatersampler` but the filtering works so the user will still get the results they are expecting.

**Comment by hohonuuli** [comment]
Hack code:

       ComboBoxListViewSkin<T> skin = new ComboBoxListViewSkin<>(comboBox);
        skin.getPopupContent().addEventFilter(KeyEvent.ANY, e -> {
            if (e.getCode() == KeyCode.SPACE) {
                e.consume();
            }
        });
        comboBox.setSkin(skin);
