### ISSUE TITLE
Quick association button

### ISSUE THREAD

**Issue by NancyJS** [mbari-media-management/vars-annotation#35]
For quick association button:

1) hover description should be renamed add quick detail button

2) when you use one that requires additional inputs (e.g., deployed-by | equipment; want to specify deployed-by manipulator
  A) it just annotates it as deployed-by equipment without asking for which equipment
  B) when you edit the detail, you cannot go down to the “To” box and cannot get anything by typing in the box, except the long scroll of every piece of equipment (rendering this method unusable for now)

**Comment by lindakuhnz** [comment]
confirmed 4/3/18

**Comment by lindakuhnz** [comment]
Just to keep track- also allow for the items to be manually re-ordered (like the observation tabs)

**Comment by hohonuuli** [comment]
Re-order feature has also been requested by DARC

**Comment by hohonuuli** [comment]
This is addressed in [release 1.1.14](https://github.com/mbari-media-management/vars-annotation/releases/tag/1.1.14)
