### ISSUE TITLE
Bulk editor causes annotations to disappear

### ISSUE THREAD

**Issue by NancyJS** [mbari-media-management/vars-annotation#37]
When you select all annotations, go to bulk editor, refresh, then change them to a different activity or group, hit enter; all of the annotations disappear. A refresh in the main window does not work to display then. Re-loading the file does not work to display them. If you re-start VARS and re-open the video, they are there (and changed).

**Comment by hohonuuli** [comment]
Yep. Confirmed this bug. Not sure what's going on yet.

**Comment by hohonuuli** [comment]
Fixed the bulk editors rename annotation. However, using undo on it also causes the annotations to disappear.

**Comment by hohonuuli** [comment]
I changed the mechanism that refreshes the view after bulk edit changes. Appears to work fine now.
