### ISSUE TITLE
GUI issues

### ISSUE THREAD

**Issue by lonnylundsten** [mbari-media-management/vars-annotation#39]
Since updating to the newest version of VARS with blue type and vertical separation bars, the GUI is very buggy. Often when data refreshes the window redraws in an obviously buggy way but eventually succeeds. However, several times window redrawing fails completely and I have to restart VARS. As an example, when I went to bulk change activity today the window was redrawn but appeared buggy when doing so. Finally, when redrawing completed, the annotations had disappeared completely and I had to restart VARS.

**Comment by hohonuuli** [comment]
Hmmm, I did a diff between alpha-7 and alpha-6. Changing the CSS for the UI shouldn't have introduced bugs. However, I did change the way we find the visible rows in the AnnotationTable. There's not built in method so I hacked something that worked. Unfortunately, the hack wouldn't compile in Java 9, so I found a workaround for the hack with a different hack. I suspect this might be what's introducing the bugs. I'll play around with it and see. See `AnnotationTableController.java`.

**Comment by hohonuuli** [comment]
First thing to try, `TableViewExt` calls recumputeVisibleIndexes twice when getting the visible rows. Change that so it only gets called once.

**Comment by lonnylundsten** [comment]
Linda also had this issue happen today. Bulk changes did not appear to function correctly, then VARS X crashed and became totally unresponsive. We restarted VARS X and opening the file revealed that the changes had in fact occurred. I don't think this bug existed in the first iteration of VARS X.

**Comment by hohonuuli** [comment]
Ok. I'll push out a new release tomorrow that reverts the `TableViewExt` usage I added. This means vars won't yet run in Java 9. Should be fine until a better working is found.

**Comment by hohonuuli** [comment]
Reverted to old method of locating visible table rows. Added Issue #40 to revisit compiling on Java 9.
