### ISSUE TITLE
User field blank and unusable

### ISSUE THREAD

**Issue by lonnylundsten** [mbari-media-management/vars-annotation#46]
@hohonuuli The user field in the VARS X annotation GUI is blank, the dropdown menu is not populated, and a user cannot manually enter a user name. This bug renders the latest VARS unusable.

**Comment by hohonuuli** [comment]
Thanks for the heads up. Just a note that that wasn't an issue in the vars-annotation. The [vars-user-server](https://github.com/mbari-media-management/vars-user-server) running on `portal` crashed. I restarted it, so It's back up and running now. I'll have to trace down why the server stopped, but it's independent of the VARS annotation app.

**Comment by lonnylundsten** [comment]
Ok. Its working again. Thanks for the fix. Maybe when you get back you can show me the steps taken to troubleshoot and, also, to restart the services  --- just so someone else in the video lab knows how to get us running when necessary.
