### ISSUE TITLE
Implement framecapture for Blackmagic Design devices

### ISSUE THREAD

**Issue by hohonuuli** [mbari-media-management/vars-annotation#49]
We were using AVFoundation to capture images from video feeds into Blackmagic Designs hardware. That doesn't work anymore. Blackmagic is pushing everyone to use their C++ SDK. VARS needs a framecapture implementation for their SDK. This is only to support real-time and tape annotations. For video annotations, framecapture is implemented in Sharktopoda and jsharktopoda.

**Comment by hohonuuli** [comment]
Requested additional resources (another coder) to work on this.

**Comment by hohonuuli** [comment]
Created:
- <https://bitbucket.org/mbari/libbmagic>
- <https://bitbucket.org/mbari/vars-blackmagic>

**Comment by hohonuuli** [comment]
When using blackmagics external boxes (rather than PCI card) we may run into the same VCR control/image capture API issue where the image capture sees the device as already in use. So it won't work with it.

**Comment by hohonuuli** [comment]
So, the lowest hanging fruit for now is to get the blackmagic API working with real-time annotations.

**Comment by hohonuuli** [comment]
We're having issues with blackmagic devices using the CamTwist/Syphoon setup.

**Comment by hohonuuli** [comment]
For tapes without epoch seconds written to the userbits, a framegrab would have a timestamp of `1970-01-01T00:00:00:00`. The image files are named `time_idx--video_reference_uuid.ext`. The time-idx was would be which ever of these was found first: recorded_timestamp, timecode, elapsedtime. Since the recorded_timestamp was always the same, it would be submitting the same name to panoptes over and over. Panoptes would say `no way` as this image URL already exists. The fix was to switch the time-idx lookup order to:

1. timecode
2. elapsed time
3. recorded timestamp

**Comment by lindakuhnz** [comment]
New VARS app just now, restarted computer, Black Siphon, Simple Client, CamTwist open, frame grabs folder mounted. Can't frame grab from D1003 (01/12/2018 dive), or V3473 (12/17/2009 dive)

**Comment by hohonuuli** [comment]
Ok. I have no trouble framecapturing from D1003-04HD usign the same setup. I'll stop by to see what's going on.

__Note: You do not need to mount the framegrabs folder__. That's no longer used by VARS.

**Comment by hohonuuli** [comment]
Note from Kyra: 

> I tested frame capture from tape on my machine and it is working.

**Comment by lindakuhnz** [comment]
1) On ALL computers (even those that are using the capture card (not the Black Magic external capture box), like the left hand one in the digital lab, you still need to use the applications Black Syphon and CamTwist. These apps have been added to that computer.

2) In VARS preferences, reset the Image Capture Input to MacOs native and Cam Twist every time you reinstall a new version of VARS.

3) USER must be selected before the frame grab icon becomes usable.

**Comment by lonnylundsten** [comment]
In the latest version of the BlackMagic designs SDK they provide a sample app called CaptureStills that might solve this issue. I built it and called it from python and java and it works great, grabs images without issues. You might want to try this again this demo did not exist before.

**Comment by hohonuuli** [comment]
Blackmagic support has been implemented in a separate MBARI internal project (libbmagic). Support for it has been added to VARS.
