### ISSUE TITLE
Merge not working

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#53]
The current code we have doesn't merge dives

**Comment by hohonuuli** [comment]
Resolved. This is actually code in:

- <https://bitbucket.org/mbari/expd/src/master/>
- <https://bitbucket.org/mbari/m3-merge-rov/src/master/>

The root issue was that merge used to require that cameradata was present in EXPD. However, there's never cameradata anymore as that requires a VCR for timecode. So the table is empty.

**Comment by lindakuhnz** [comment]
Using this protocol, I'm not able to merge this morning. How is the # getting introduced?
1. Install  Docker - https://www.docker.com
2. Start Docker
3. Open a Terminal
4. Start the merge console:
 docker run -it portal.shore.mbari.org:5000/portal/m3-merge-rov /bin/bash
5.  In the console, merge
cd /opt/m3-merge-rov/bin 
 ./merge_expd  <ROV> <DIVE> 
e.g. ./merge_expd “Doc Ricketts” 953
-----------------------------------
Last login: Wed Apr  4 10:33:46 on ttys001
yoda:~ linda$ docker run -it portal.shore.mbari.org:5000/portal/m3-merge-rov /bin/bash
root@1743207fd910:/# cd /opt/m3-merge-rov/bin
root@1743207fd910:/opt/m3-merge-rov/bin# ./merge_expd Ventana 4110
bash: ./merge_expd: No such file or directory
root@1743207fd910:/opt/m3-merge-rov/bin#

**Comment by hohonuuli** [comment]
Run the command below, then try again. This will grab the latest update.

`docker pull portal.shore.mbari.org:5000/portal/m3-merge-rov`
