### ISSUE TITLE
At sea annotations are not loaded to video segments

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#56]
See V4110. All of the annotations made at sea did not get disbursed amongst the various video segments. They are still under 4110 "real-time". Checked each segment with the "show concurrent annotations" box checked.

Should I (and/or could I?) move these? Should they be getting moved at registration?

**Comment by hohonuuli** [comment]
Don't move them. They should not get moved; real time annotations stay under the real-time video reference. The `duration` property did not get set on the realtime video reference like it was supposed to. Once that's set everything will work as expected. I'm looking into why that didn't get set.

**Comment by hohonuuli** [comment]
Fixed. There's a new release in my tempbox. When you open a video file and click `show cuncurrent annotation` the realtime annotations __that occur only during that video file__ will be shown.
