### ISSUE TITLE
GUI usability: Observation input box

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#57]
On hold per Brian, but want to track; we need to explore options at some point.

When taking a frame grab, then annotating the observation, the box to start typing in is not delineated visually. Any quick fix for this (adding a white line around it)? 

Brian: No quick fix. I’ve looked into this … when I used the same widget in isolated tests it shows a red highlight when it is enable/has focus. But this disappears when used in the annotation UI. Not sure why yet.

**Comment by hohonuuli** [comment]
Relevant code:

- Demo is [FilteredComboBoxDecoratorDemo.java](https://github.com/mbari-media-management/vars-annotation/blob/master/src/test/java/org/mbari/m3/vars/annotation/ui/shared/FilteredComboBoxDecoratorDemo.java)
- App is [AnnotationEditorPaneController.java](https://github.com/mbari-media-management/vars-annotation/blob/master/src/main/java/org/mbari/m3/vars/annotation/ui/roweditor/AnnotationEditorPaneController.java#L145)
