### ISSUE TITLE
Video tape testing: moving annotations

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#61]
Want to test how this works with video tapes. Test, merge etc. 

Tried to move annotations from one dive to another. I can't see how to do this. In bulk editor, the move frames drop down menu doesn't list the dive I want them to go to. That dive has an annotation in it, so I know it exists in the new database.

Also, unclear as how we would change them to same dive, different tape number.

**Comment by lindakuhnz** [comment]
Newly created dive/tapes numbers are not automatically created nor refreshed to the list of available places to move them to unless you close VARSX.

For now: If a tape number has never been opened before, you have to open it so that it registers, close VARS to refresh the list, then it is available for use in moving annotations.

**Comment by lonnylundsten** [comment]
This should be reopened. There is no way to move annotations from one tape set to a new tape set. If a tape set exists already you can move annotations as expected. If not, you have to create a new real time annotation set and move all of them to that set; there appears to be no way to create a new tape set -- maybe this has to be done with a deck on through the browse to tape window? If so, that means to simply move dives I have to sit down and open up all the tape sets at a station that has a deck. In the old vars I could simply select annotations and move them wherever I want even if that tape set didn't exist the move process would do that for me.

**Comment by hohonuuli** [comment]
This is related to #25
