### ISSUE TITLE
Seek doesn't function

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#66]
Right click on an annotation to seek. . .

**Comment by lindakuhnz** [comment]
Update: Kyra says it is working for tape. 

I'm working on files. It works every once in a while, but not consistently. This is **extra necessary** because the gui shows us GMT and the video in sharktopoda shows time elapsed within the 15 minute chunk of video. We have no way of knowing how to get to (example) 18:58:53:.665 in the chunk of video we are working on.

**Comment by hohonuuli** [comment]
@lindakuhnz Can you please include the video that is causing problems and how you're connected to it. For example, if you are working with a large ProRes file that's connected via the web server (instead of browsing to a local file), seek will fail because the server can't stream the ProRes file fast enough.

**Comment by lindakuhnz** [comment]
Connected via local file, yes pro-res

**Comment by hohonuuli** [comment]
Can you post the path to the file that shows the issue. Also, were you browsing to it on \\Atlas or did you copy it to your local drive?

**Comment by lindakuhnz** [comment]
browsing on atlas - all files

**Comment by lindakuhnz** [comment]
V4110_20180402T201040z_prores.mov browsed to atlas from "browse to local video). Does not seek just now.

**Comment by lindakuhnz** [comment]
Seek is working for in lab annotations. Seek does not work on annotations taken at sea (because there is no elapsed time?).

**Comment by hohonuuli** [comment]
Have to look into this but I think I'll need to calculate the elapsedTime from the recordedTimestamp in order for this to work correctly.

**Comment by hohonuuli** [comment]
Users can now seek real-time annotations to point in current media. Change set: c13b86b
