### ISSUE TITLE
Select multiple annotations

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#67]
Used to be able to select (I think using command) multiple, non-contiguous annotations.
Along the same lines, used to be able to select a line, then drag down to select one or more contiguous annotations (for copying a group of annotations).

**Comment by lindakuhnz** [comment]
If you select observation, you can control click to select non-contiguous annotations. Please change this to selection of anywhere on the line. 

Control click doesn't work to select a line, then drag down to select one or more contiguous annotations (for copying a group of annotations).

**Comment by lindakuhnz** [comment]
This works now (as a result of other changes).

**Comment by hohonuuli** [comment]
Fixed in [0.2.1](https://github.com/mbari-media-management/vars-annotation/releases/tag/0.2.1)
