### ISSUE TITLE
keyboard shortcuts don't work

### ISSUE THREAD

**Issue by lonnylundsten** [mbari-media-management/vars-annotation#7]
The keyboard shortcuts are not working in the beta version of the new VARS. 
Please add:
Command-N (New annotation)
Command-C (Copy annotation)
Command-T (Copy annotation time)
Command-F (frame grab)

**Comment by hohonuuli** [comment]
Added these. Also just a note that [Control]-[space] starts and stops video playing. Note that it is `control` __not__ `command` as [Command]-[space] launches spotlight on macs.

**Comment by hohonuuli** [comment]
Also note that [Command]+up and [Command]+down navigate the table.

**Comment by lonnylundsten** [comment]
Can you also implement command-delete as a keyboard shortcut for deleting annotations?

**Comment by hohonuuli** [comment]
Will do ...

**Comment by hohonuuli** [comment]
Done

**Comment by lonnylundsten** [comment]
I said to use 'Command-C' for copy annotations, but that should be 'Command-G' as it is in the current version of VARS. Also, having Command-C is preventing other copy functions, which I hope will be fixed by remapping the copy annotation key command.

**Comment by hohonuuli** [comment]
Resolved
