### ISSUE TITLE
Annotation links in expedition database are not working with VARS X

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#73]
The annotations links in the expd are not getting created for newer dives, because they are probably pointing at the old database.  Do we need to do something (or have Mike McCann) do something to fix this?

**Comment by hohonuuli** [comment]
This is Mike McCann/ Karen Salamy issue. They probably can't tackle this until we've completed the migration of annotations from the VARS to the M3_ANNOTATIONS database.

**Comment by lindakuhnz** [comment]
Left a message with Mike 1/23 and again today to see if he can update the links now.

**Comment by lindakuhnz** [comment]
On Mar 5, 2019, 11:59 AM -0800, Mike McCann <mccann@mbari.org>, wrote:
Hi Lonny,

Thanks for the “decoding key”.

I wonder if it might be possible to provide a new View in M3_Annotations that does the aliasing and delivers the legacy column names, maybe call it “Annotations_legacy”?

-Mike

On Mar 5, 2019, at 11:34 AM, Lonny Lundsten <lonny@mbari.org> wrote:

Mike,
These are the changes that are relevant to expdb:

server=perseus,1433;DATABASE=M3_Annotations
conceptname is now concept
depth is now depth_meters
tapetimecode is now index_timecode 
recordeddate is now index_recorded_timestamp
videoarchivename is now video_name
image is now image_url
cameradirection is now activity
We should probably add dive_number or video_sequence_name

If interested, I can probably change the .asp code and test functionality. If you like that idea, I will probably need write permission to do so. If not, no worries.

Thanks,
LL


Lonny Lundsten
Senior Research Technician
Monterey Bay Aquarium Research Institute

7700 Sandholdt Road
Moss Landing, CA 95039
Phone: (831) 775-1762
lonny@mbari.org

On Mar 5, 2019, at 10:44 AM, Linda Kuhnz <linda@mbari.org> wrote:

Yes - everything is in M3 annotations on Perseus now, but I’ll let Brian point you to the new correct place just so I don’t set you in the wrong direction or wrong timing. Thanks much-

On Mar 5, 2019, at 10:37 AM, Mike McCann <mccann@mbari.org> wrote:

Hi Linda,

I think I’ll need some help with more information about the VARS conversion and what needs to be changed in the annotations.asp script.

It’s currently querying the Annotations view on Server=perseus,1433;DATABASE=VARS; and the last annotation in that view is on 1/27/2018 5:55:52 PM.

How does this need to be changed?

-Mike

--
Mike McCann
Software Engineer
Monterey Bay Aquarium Research Institute
7700 Sandholdt Road
Moss Landing, CA 95039-9644
Voice: 831.775.1769  Fax: 831.775.1736 http://www.mbari.org

On Jan 23, 2019, at 2:15 PM, Linda Kuhnz <linda@mbari.org> wrote:

Hi Mike-

Now that the VARS conversion has taken place, can you add back the annotation links in the expedition database? It is still pointing to the old VARS database (and thus new dives haven’t had links since we started with video files). Also, does anything have to change with VFCBYDIVE? Does it need to look to the new database to decide when a change has taken place?

Thanks-
Linda Kuhnz------------------------
Hi Mike,

> I wonder if it might be possible to provide a new View in M3_Annotations that does the aliasing and delivers the legacy column names, maybe call it “Annotations_legacy”?

I’ve created a new view named `annotations_legacy` in M3_ANNOTATION with the exact same column names as the `Annotations` view in the old VARS database. Here’s some gotchas to be aware of:

1. TapeTimeCode - Not every annotation will have a TapeTimeCode anymore. Timecodes are only applicable to tape annotations, not video-file annotations.

2. videoArchiveName - There’s no longer a unique video name for each video. Instead, I’m returning the URI of the video. This could be in one of three forms:
 a. Tape - urn:tid:mbari.org:D0608-02HD
 b. Video - http://m3.shore.mbari.org/videos/M3/master/DocRicketts/2018/04/1015/D1015_20180420T161421Z_prores.mov
 c. Real-time - urn:rtva:org.mbari:Doc_Ricketts_1015

3. AnnotationMode - Not `o` and ‘d’ anymore. 

4. ChiefScientist - Isn’t actively populated yet.  That’s on my TODO list
-- B

**Comment by lindakuhnz** [comment]
Hi Mike, 

Yes, I can do that with a few caveats. There isn’t an exact 1-to-1 correspondence of data between the old and new vars systems. For example, the M3 system uses `deployment id` instead of the Rov-name/dive-number. For example a deployment id might be `Ventana 1234` or `i2MAP 20161212`. I’ll throw up a view and we can figure it out form there.

Cheers

-- B

**Comment by lindakuhnz** [comment]
Mike McCann and Brian fixed this today.

**Comment by hohonuuli** [comment]
Added views that mimic the old Vars views.
