### ISSUE TITLE
Framegrab does not attach to multiple annotations at the same elapsed time

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#77]
Replicate VARS function: When you create a frame grab and do not advance the video, multiple annotations should be attached to the same frame grab.

**Comment by hohonuuli** [comment]
Got it. Here's what's going on - for my notes.

The framegrab is attached to multiple annotations. However, only the one created is updated in the UI, the others at the same time need to be refreshed and re-read from the annotation server. Need to add code to recognize the related annotations, fetch them, remove the existing ones and replace them with the udpated ones.

**Comment by hohonuuli** [comment]
__IMPORTANT__ Major testing of framecapture required after rework!!!

**Comment by hohonuuli** [comment]
Verified the framegrabs get attached to the all annotations with the __exact__ same _elapsed time_ index. __However__, I've noted that even when you seek to a point in the video and then take a framegrab their may be some offset in the 10s of microseconds so the the framegrab annotation may be offset from the annotation that was `seeked` to.
