### ISSUE TITLE
Bulk editor changes do not update observer

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#79]
Bulk editor should change the observer to the currently signed in user when making updates to annotations

**Comment by NancyJS** [comment]
Agreed, this is a critical feature to reinstate into VARS. We always want to track observer and each of their annotations over time. Thanks!

**Comment by hohonuuli** [comment]
My understanding is that the changes that @lindakuhnz is referring to is that when she changes the `group` or `activity` (e.g. changes annotations from `transect` to `descend`) the user is not being updated. We had previously had a discussion about this and the consensus was that in those cases the user should __not__ be changed. 

For other cases, such as when the bulk editor is used to change the concept, the user is changed. 

__So please clarify what the correct behavior should be for changing groups and activities.__

**Comment by hohonuuli** [comment]
Relevant code:

1. [UpdateAnnotationsCmd.java](https://github.com/mbari-media-management/vars-annotation/blob/master/src/main/java/org/mbari/m3/vars/annotation/commands/UpdateAnnotationsCmd.java#L67)
2. [ChangeActivityCmd.java](https://github.com/mbari-media-management/vars-annotation/blob/master/src/main/java/org/mbari/m3/vars/annotation/commands/ChangeActivityCmd.java)

**Comment by lindakuhnz** [comment]
Just changed an annotation to 1-gallon paint bucket, but observation doesn't not change. See attached.
Yes, confirming no observer change for activity.
<img width="1293" alt="untitled" src="https://user-images.githubusercontent.com/38045059/43859366-412139f2-9b05-11e8-95e3-8ff39f0ce36c.png">

**Comment by lindakuhnz** [comment]
Meant observer doesn't not change. I changed the annotation via bulk editor.

**Comment by hohonuuli** [comment]
Found bug. Fixed. See change set above. New release in \\Atlas\Tempbox\brian\shore
