### ISSUE TITLE
Annotations don't open in VARSX

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#80]
D1042 first file opens and concurrent annotations appear. Subsequent annotation don't appear in individual 15 minutes chunks. The grid view shows annotations throughout the dive. I’ve tried a few times today and had Lonny try as well.

**Comment by lonnylundsten** [comment]
Annotations also appear in the SQL db, I verified this by running a script on the db. Annotations don't show in VARS. Come down to the VL ASAP to see for yourself.

**Comment by hohonuuli** [comment]
Looking into it

**Comment by hohonuuli** [comment]
Found the issue. I ran a quick check of the dive using the web API at <http://m3.shore.mbari.org/vam/v1/videosequences/name/Doc%20Ricketts%201042> and found the media for real-time annotations:

```javascript
{
      "name": "Doc Ricketts 1042 real-time",
      "start_timestamp": "2018-07-24T20:04:49.687Z",
      "duration_millis": 1850827,
      "video_references": [
        {
          "uri": "urn:rtva:org.mbari:Doc_Ricketts_1042",
          "width": 0,
          "height": 0,
          "frame_rate": 0.0,
          "size_bytes": 0,
          "last_updated_time": "2018-07-24T12:53:10Z",
          "uuid": "f6cdb051-15bc-442a-8dbe-97ef78cd7e73"
        }
      ],
      "last_updated_time": "2018-07-24T13:36:55Z",
      "uuid": "a76a1fef-aa50-4e58-986f-2f78c725f3f1"
    }
``` 

Notice the duration millis ... 1850827 = 30 minutes, 50.827 seconds. So the annotation system is looking for concurrent annotations between 2018-07-24T20:04:49.687Z and 2018-07-24T20:35:40.514Z. Which only overlaps with the 1st 3 videos (and barely the 3rd).

I've fixed this. __It's also a very simple fix that you can do for yourselves in the future. The fix instructions are__:
  1. __Open the realtime annotations for the dive (`Doc Ricketts 1042 real-time`) in VARS__. 
  2. __Close it__ or open a different video. This will automatically adjust the time-bounds for real-time annotations.

I don't know why the correct time didn't get set. They might have left VARS open at the end of the cruise. In which case the database never got updated with the correct duration for the real-time media.

**Comment by hohonuuli** [comment]
@lindakuhnz @lonnylundsten Can you amend the ship board instructions to mention that annotators should shut down VARS when the cruise is done. Thanks
