### ISSUE TITLE
Default to "Show concurrent annotations:

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#81]
Please set the check box to be the default.

**Comment by hohonuuli** [comment]
For performance and stability reasons, I believe this is a very, very bad idea. There will be cases where there are 1000's of annotations (e.g. tapes) that may cause the UI to hang and become unusable.

**Comment by lindakuhnz** [comment]
Let's talk about this. If we are opening a dive, we want to see all of the annotations, even if there are thousands. I personally can't think of a time I would want to see all annotations from a dive. Can other's give their opinions please?
