### ISSUE TITLE
Prior to combining databases: identify pessimistic merges

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#82]
Since the preliminary plan is to eventually allow all dives to re-merge once they come into the new database, this is a reminder to identify and replicate dives with pessimistic merges.

**Comment by lindakuhnz** [comment]
Does the closing of this ticket mean that yes, this is part of the plan, or no, it won't be done?  Thanks-

**Comment by hohonuuli** [comment]
It was always part of the plan.

**Comment by lindakuhnz** [comment]
Awesome. . .

**Comment by hohonuuli** [comment]
Code for this migration is in a MBARI (private) repository at [migrate_mrege_status.py](https://bitbucket.org/mbari/m3-utils/src/master/src/python/migrate_merge_status.py)
