### ISSUE TITLE
Annotation GUI jumps to incorrect row after changing an annotation

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#83]
Similar to what we fixed in the old VARS (VARS-95)
When you make changes to a line of annotation e.g., update the object name, the cursor pops you to another row (not where you had been annotating). Having the cursor stay in the same area/row you were working is much easier.

**Comment by lindakuhnz** [comment]
Hold on this; I'd test more to tell you exactly what it is doing/not doing

**Comment by hohonuuli** [comment]
This no longer seems to be an issue.
