### ISSUE TITLE
No at sea annotations for D1007-D1013

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#84]
The annotations made at sea are not in VARS X

**Comment by hohonuuli** [comment]
These annotations are not in the shore database or on the ship database (alaskanwind). Do you know who was annotating for those dives? Were these Kakani's dives? I looked for all deployments for Kakani using:

```sql
SELECT DISTINCT
    video_sequence_name,
    video_name
FROM
    annotations
WHERE
    observer = 'kakani'
```

But only got:

```
i2MAP 20170622   i2MAP 20170622 20170622T173833Z
Mini ROV 0115    Mini ROV 0115 real-time
```

**Comment by lindakuhnz** [comment]
Apologies- they are Sudek (example D1009). I just realized that these were duding the tap/file transition and they are on tape, so I'll see what the current protocol is for transferring the annotations into new VARS (I haven't done it before).
