### ISSUE TITLE
Map spacebar to the play button

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#86]
For annotation efficiency, please map the keyboard space bar to the play button so that we can stop and start the video playing. Right now you have to have Sharktopoda selected for the spacebar to work.

**Comment by hohonuuli** [comment]
Use ctrl-space when the annotation app is focused. Can't make space bar without a modifier when used as a good shot cut.

**Comment by lindakuhnz** [comment]
Works!
