### ISSUE TITLE
VARS X merge; update instructions

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#88]
Current Arguments:
   rovName = The name of the ROV (e.g. "Doc Ricketts")
   diveNumber = The dive number for the dive to be merged

Script requites the use of 'Doc Ricketts" vs  "Doc Ricketts". Can you update the argument text? Thanks.

**Comment by lonnylundsten** [comment]
The steps for doing this are located here. Brian will verify that the code has not changed today. https://mww.mbari.org/itd/video/vars_scripts/docker/varsx_dive_merge.html

**Comment by lonnylundsten** [comment]
OK to close

**Comment by hohonuuli** [comment]
## Updated instructions

- Note the container is no longer tagged with _portal_, it uses _mbari_ instead.
- `merge_expd` is now `merge_rov`

### Instructions

This script will allow you to manually merge dive data with observations using a shell within a Docker container.

1. Install Docker Community Edition (CE, free)
2. Start Docker
3. Open a terminal and run: 
```docker pull portal.shore.mbari.org:5000/mbari/m3-merge-rov```
4. Start the merge console by typing in terminal: 
```docker run -it portal.shore.mbari.org:5000/mbari/m3-merge-rov /bin/bash```
5.  In the merge console, change directories: 
```cd /opt/m3-merge-rov/bin```
6. In the merge console the expedition data: 
```./merge_rov <'ROV_Name'> <'Dive Number'> ```

Examples:
```
./merge_rov 'Doc Ricketts' 953
./merge_rov Ventana 4110
``` 

To display help, run `./merge_rov -h`:

```
Usage: merge_rov [-hV] [-d=<toleranceSeconds>] [-t=<timeoutSeconds>] ROVNAME
                 DIVENUMBER
Merge a single MBARI ROV dive with ancillary data from the EXPD database. This
includes merge with position, ROV pose, and CTD data.
      ROVNAME      The ROV Name. If it has a space wrap it in quotes.
                   ('Doc Ricketts', Ventana, Tiburon)
      DIVENUMBER   The dive number. e.g. 1234 or 654
  -d, --tolerance=<toleranceSeconds>
                   Tolerance for finding nearest expd data log record (default: 7.0)
  -h, --help       Show this help message and exit.
  -t, --timeout=<timeoutSeconds>
                   Timeout for web service calls in seconds. (default: 600)
  -V, --version    Print version information and exit.
```
