### ISSUE TITLE
Activity changes don't work

### ISSUE THREAD

**Issue by lonnylundsten** [mbari-media-management/vars-annotation#9]
When changing activity, these changes don't actually effect the lines of annotation. Changes don't take effect when entered in main GUI window or in the bulk editor window. It seems like its not actually working but maybe I just don't understand how to use it?

**Comment by hohonuuli** [comment]
Do the following:

1. Select the rows you want to change in the table
2. Click the `Refresh` button on the bulk editor tab. This will populate the dialogs with acceptable values
3. In the bulk editor tab, select the group or activity you want to change the rows to.

**Comment by hohonuuli** [comment]
Note that it's a little different in the old VARS in that I'm getting rid of duplicate ways to do the same thing, so using the group and activity at the bottom of the window only change the value that new annotations use.

**Comment by lonnylundsten** [comment]
Great. That worked!
LL

Lonny Lundsten
Senior Research Technician

Monterey Bay Aquarium
Research Institute
7700 Sandholdt Road
Moss Landing, CA 95039
Phone: (831) 775-1762
email: lonny@mbari.org
