### ISSUE TITLE
Play bar icon goes whacky

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#91]
We've all seen this together. icon moves back and forth rapidly. See movie file IMG_0190.MOV in video lab tempbox (can't attach here)

**Comment by hohonuuli** [comment]
This a bug in Sharktopoda. It's currently being tracked at https://sharing.clickup.com/t/h/qb0g0k/W3H7UFP2F8IUCXT

**Comment by hohonuuli** [comment]
This has not been reported with the last few iterations of VARS and Sharktopoda 2
