### ISSUE TITLE
Images cannot be downloaded from VARS X query

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#97]
The normal command to "save images" after doing a VARS query is not working for the M3 system. The function normally puts a folder on your desktop (or whatever path), then puts a physical copy of the .jpg in a vehicle/dive number folder combo. When this is executed it builds the directories but no physical copy of the framegrabs is included (see attached). Might be related to this?: Note that the "stills" folders contain only symbolic links, while the "images folders" contain the physical copy of the framegrabs).

![untitled](https://user-images.githubusercontent.com/38045059/48018027-9e6e6380-e0e4-11e8-8749-daf771b6fc2d.png)

**Comment by hohonuuli** [comment]
Moved to vars-query repo
