### ISSUE TITLE
Chief Scientist doesn't show in VARS X query

### ISSUE THREAD

**Issue by lindakuhnz** [mbari-media-management/vars-annotation#98]
See attached. Not all chief scientists with dives loaded to VARS X are listed for query (example: Ken Smith)
![screen shot 2018-11-19 at 12 45 16 pm](https://user-images.githubusercontent.com/38045059/48734261-cc31cd00-ebf9-11e8-88cc-f7b416d663a5.png)

**Comment by hohonuuli** [comment]
Moved to vars-query repo
